package data.api.dto.chatGpt

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data Transfer Object for Chat GPT request.
 *
 * @property id The ID of the request.
 * @property model The model to use for the request (e.g. "gpt-3.5-turbo").
 * @property created The timestamp of when the request was created.
 * @property choices The list of choices generated by the model.
 */
@Serializable
data class ChatGptResponseDto(
    @SerialName("id")
    val id: String,
    @SerialName("object")
    val obj: String,
    @SerialName("created")
    val created: Long,
    @SerialName("model")
    val model: String,
    @SerialName("choices")
    val choices: List<ChatGtpChoiceDto>
)