package data.api.dto.chatGpt

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data Transfer Object for Chat GPT response choice.
 *
 * @property index The index of the choice.
 * @property finishReason The reason the request finished.
 * @property message The message generated by the model.
 *
 */
@Serializable
data class ChatGtpChoiceDto(
    @SerialName("index")
    val index: Int,
    @SerialName("finish_reason")
    val finishReason: String,
    @SerialName("message")
    val message: ChatGptMessageDto
)