package domain.model.monster

import domain.model.Alignment
import domain.model.Condition
import domain.model.CreatureSize
import domain.model.CreatureType
import domain.model.DamageType
import domain.model.Environment

data class Monster(
    val key: String,
    val name: String,
    val isFavorite: Boolean,
    val challenge: Challenge,
    val size: CreatureSize,
    val type: CreatureType,
    val alignment: Alignment,
    val armorsClass: Int,
    val hitPoints: Int,
    val charisma: Int,
    val charismaSave: Int? = null,
    val dexterity: Int,
    val dexteritySave: Int? = null,
    val constitution: Int,
    val constitutionSave: Int? = null,
    val intelligence: Int,
    val intelligenceSave: Int? = null,
    val strength: Int,
    val strengthSave: Int? = null,
    val wisdom: Int,
    val wisdomSave: Int? = null,
    val walkSpeed: Double,
    val swimSpeed: Double,
    val flySpeed: Double,
    val climbSpeed: Double,
    val burrowSpeed: Double,
    val hover: Boolean = false,
    val arcana: Int? = null,
    val acrobatics: Int? = null,
    val animalHandling: Int? = null,
    val deception: Int? = null,
    val history: Int? = null,
    val insight: Int? = null,
    val intimidation: Int? = null,
    val investigation: Int? = null,
    val medicine: Int? = null,
    val nature: Int? = null,
    val perception: Int? = null,
    val performance: Int? = null,
    val persuasion: Int? = null,
    val religion: Int? = null,
    val sleightOfHand: Int? = null,
    val stealth: Int? = null,
    val survival: Int? = null,
    val nonMagicalAttackResistance: Boolean,
    val nonMagicalAttackImmunity: Boolean,
    val damageVulnerabilities: List<DamageType>,
    val damageResistances: List<DamageType>,
    val damageImmunities: List<DamageType>,
    val conditionImmunities: List<Condition>,
    val passivePerception: Int,
    val sightRange: Double,
    val darkVisionRange: Double? = null,
    val blindSightRange: Double? = null,
    val tremorSenseRange: Double? = null,
    val trueSightRange: Double? = null,
    val languages: List<String>,
    val traits: List<Trait>,
    val actions: List<Action>,
    val bonusActions: List<Action>,
    val reactions: List<Action>,
    val legendaryActions: List<Action>,
    val environments: List<Environment>,
)

